### ISSUE TITLE
Bad Cerificiate

### ISSUE THREAD

**Issue by ottolewis8** [mfakih294/Nibras-PKM#3]
Downloaded and run
https://github.com/mfakih294/Nibras-PKM/releases/download/v1.4.6/nibras-windows.zip

In browser: https://localhost:1441/nibras
Getting:ERR_CERT_AUTHORITY_INVALID
Bad certificate error

Also:
06-Jan-2021 17:21:10.474 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[HTTP/1.1-8080]]
        org.apache.catalina.LifecycleException: Protocol handler initialization failed
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:983)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1057)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:584)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:607)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:303)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: java.net.BindException: Address already in use: bind
                at sun.nio.ch.Net.bind0(Native Method)
                at sun.nio.ch.Net.bind(Net.java:433)
                at sun.nio.ch.Net.bind(Net.java:425)
                at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
                at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
                at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:230)
                at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:213)
                at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1142)
                at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1155)
                at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:575)
                at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:980)
                ... 13 more

**Comment by mfakih294** [comment]
The bundled certificate is self-signed. So you may safely accept it and proceed, bypassing any warning.

As for the port, it seems port 8080 is already in use on your machine. You may edit /nibras/tomcat/conf/server.xml, change 8080 port in it to something else, e.g. 8083, then launch start.bat again.

Last note: the latest version is now at this URL: 
https://github.com/mfakih294/Nibras-PKM/releases/tag/v1.2.7
(Sorry, some version mislabeling made 1.4.6 look like the latest version).
